 --  Demographics Enrolment flat TABLE for migrating the enrolments
DROP TABLE IF EXISTS tbl_m_demographics;
CREATE TABLE tbl_m_demographics
SELECT implementing_partner_id,date_of_enrollment,verification_document_id,verification_document_other,verification_doc_no,marital_status_id
,phone_number,dss_id_number,county_of_residence_id,sub_county_id,ward_id,informal_settlement,village,landmark,dreams_id,guardian_name,relationship_with_guardian,
guardian_phone_number,guardian_national_id,external_organisation_id,cpmis_id,nemis_no,nupi_no
 FROM dreams_production.DreamsApp_client where voided=0 ;
 
  -- household
DROP TABLE IF EXISTS tbl_m_household;
CREATE TABLE tbl_m_household
SELECT client_id,head_of_household_id,head_of_household_other,age_of_household_head,is_father_alive,is_mother_alive,is_parent_chronically_ill
,main_floor_material_id,main_roof_material_id,main_roof_material_other,main_wall_material_id,main_wall_material_other
,source_of_drinking_water_id,source_of_drinking_water_other,no_of_days_missed_food_in_4wks_id,has_disability_id,disabilitytype_id,disability_type_other,no_of_people_in_household,no_of_females,no_of_adults,no_of_males,
no_of_children,ever_enrolled_in_ct_program_id,currently_in_ct_program_id,current_ct_program
 FROM dreams_production.DreamsApp_clientindividualandhouseholddata hd
 Inner join DreamsApp_client c on hd.client_id=c.id
 Left join DreamsApp_clientindividualandhouseholddata_disability_type dt on hd.id=dt.clientindividualandhouseholddata_id where hd.voided=0;
 
 
 -- Education and Employment
DROP TABLE IF EXISTS tbl_m_edu_empl;
CREATE TABLE tbl_m_edu_empl
SELECT client_id,currently_in_school_id,current_school_name,current_school_type_id,current_school_level_id,current_school_level_other,
current_class,educationsupporter_id,current_education_supporter_other,current_income_source_id,current_income_source_other,has_savings_id,banking_place_id,banking_place_other,
reason_not_in_school_id,reason_not_in_school_other,last_time_in_school_id,dropout_school_level_id,dropout_class,life_wish_id,life_wish_other
FROM dreams_production.DreamsApp_clienteducationandemploymentdata ce
left join DreamsApp_clienteducationandemploymentdata_current_educationebf4 esp on ce.id=esp.clienteducationandemploymentdata_id where ce.voided=0;
 
 
 -- hiv testing 
CREATE TABLE tbl_m_hivtesting
SELECT client_id,ever_tested_for_hiv_id,period_last_tested_id,last_test_result_id,ccc_no,enrolled_in_hiv_care_id,care_facility_enrolled,reason_not_in_hiv_care_id,reason_not_in_hiv_care_other,
reasonnottestedforhiv_id,reason_never_tested_for_hiv_other,knowledge_of_hiv_test_centres_id
from dreams_production.DreamsApp_clienthivtestingdata ht
left join DreamsApp_clienthivtestingdata_reason_never_tested_for_hiv rnt on ht.id=rnt.clienthivtestingdata_id where ht.voided=0;

-- sexual activity
DROP TABLE IF EXISTS tbl_m_sexualactivity;
CREATE TABLE tbl_m_sexualactivity
SELECT client_id,ever_had_sex_id,age_at_first_sexual_encounter,has_sexual_partner_id,sex_partners_in_last_12months,age_of_last_partner_id,
age_of_second_last_partner_id,age_of_third_last_partner_id,last_partner_circumcised_id,second_last_partner_circumcised_id,third_last_partner_circumcised_id,
know_last_partner_hiv_status_id,know_second_last_partner_hiv_status_id,know_third_last_partner_hiv_status_id
used_condom_with_last_partner_id,used_condom_with_second_last_partner_id,used_condom_with_third_last_partner_id,received_money_gift_for_sex_id
FROM dreams_production.DreamsApp_clientsexualactivitydata where voided=0;

-- reproductive health
DROP TABLE IF EXISTS tbl_m_reprohealth;
CREATE TABLE tbl_m_reprohealth
 SELECT client_id,has_biological_children_id,no_of_biological_children,currently_pregnant_id,current_anc_enrollment_id,anc_facility_name,fp_methods_awareness_id
,familyplanningmethod_id,known_fp_method_other,currently_use_modern_fp_id,current_fp_method_id,current_fp_method_other,reason_not_using_fp_id,reason_not_using_fp_other
 FROM dreams_production.DreamsApp_clientreproductivehealthdata rp
 Left join DreamsApp_clientreproductivehealthdata_known_fp_method rpm on rp.id=rpm.clientreproductivehealthdata_id where rp.voided=0;
 
 -- violence against women
DROP TABLE IF EXISTS tbl_m_violence;
CREATE TABLE tbl_m_violence
SELECT client_id,humiliated_ever_id,humiliated_last_3months_id,threats_to_hurt_ever_id,threats_to_hurt_last_3months_id,insulted_ever_id,insulted_last_3months_id 
,economic_threat_ever_id,economic_threat_last_3months_id,physical_violence_ever_id,physical_violence_last_3months_id,physically_forced_sex_ever_id,physically_forced_sex_last_3months_id,
physically_forced_other_sex_acts_ever_id,physically_forced_other_sex_acts_last_3months_id,threatened_for_sexual_acts_ever_id,threatened_for_sexual_acts_last_3months_id,hp.gbvhelpprovider_id,
gbv_help_provider_other,php.gbvhelpprovider_id as preferred_gbv_help_provider,preferred_gbv_help_provider_other
FROM dreams_production.DreamsApp_clientgenderbasedviolencedata gb
Left join DreamsApp_clientgenderbasedviolencedata_gbv_help_provider hp on gb.id=hp.clientgenderbasedviolencedata_id
left join DreamsApp_clientgenderbasedviolencedata_preferred_gbv_help_p1bce php on gb.id=php.clientgenderbasedviolencedata_id where gb.voided=0;

-- drug use
DROP TABLE IF EXISTS tbl_m_druguse;
CREATE TABLE tbl_m_druguse
SELECT client_id,used_alcohol_last_12months_id,frequency_of_alcohol_last_12months_id,drug_abuse_last_12months_id,du.drug_id,drug_abuse_last_12months_other,
drug_used_last_12months_other,produced_alcohol_last_12months_id
FROM dreams_production.DreamsApp_clientdrugusedata cd
left join DreamsApp_clientdrugusedata_drug_used_last_12months du on cd.id=du.clientdrugusedata_id
where cd.voided=0;

-- program participation
DROP TABLE IF EXISTS tbl_m_programp;
CREATE TABLE tbl_m_programp
SELECT client_id,dreamsprogramme_id,dreams_program_other FROM dreams_production.DreamsApp_clientparticipationindreams m
left join DreamsApp_clientparticipationindreams_dreams_program pms on m.id=pms.clientparticipationindreams_id
where voided=0;
 